# Generated by Django 3.0 on 2020-06-30 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField()),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Advertiser')),
            ],
        ),
    ]
